[package]
name = "ror"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "ror"
path = "lib.rs"


[dependencies]
anyhow = "1.0.67"
ror-sys = {path = "ror-sys"}


[[example]]
name = "basic"
